sudo: required
dist: trusty
language: minimal

services:
  - docker

before_script:
  - docker build . -t exhaustive -f Dockerfile

script:
  - docker run -t exhaustive /ccp4/bin/ccp4-python -m unittest discover test
after_script:
  - docker images

