sudo: required
services: docker
install: docker build github.com/nelse003/ccp4_phenix_docker
script: docker run github.com/nelse003/ccp4_phenix_docker "/ccp4/bin/ccp4_python /exhaustive_search/compile_test.py"
