sudo: required
services: docker
install: docker build github.com/nelse003/ccp4_phenix_docker
script: docker run nelse003/ccp4_phenix_docker /bin/bash -c "/ccp4/bin/ccp4_python /exhaustive_search/compile_test.py"
