sudo: required
services: 
- docker

install: 
- docker build --tag ccp4_phenix_docker .

script: 
- docker run ccp4_phenix_docker /bin/bash -c "/ccp4/bin/ccp4-python /exhaustive_search/compile_test.py"

after_script:
- docker images

before_deploy:
-docker login -u "$REGISTRY_USER" -p ""$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push nelse003/ccp4_phenix_docker
  on:
branch: master
