sudo: required
dist: trusty
language: minimal

services: 
- docker

before_script: 
- docker image prune
- docker pull nelse003/ccp4_phenix_docker || true
- docker build --pull --cache-from nelse003/ccp4_phenix_docker --tag nelse003/ccp4_phenix_docker .

script: 
- docker run nelse003/ccp4_phenix_docker /bin/bash -c "/ccp4/bin/ccp4-python /exhaustive_search/compile_test.py"

after_script:
- docker images

before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push nelse003/ccp4_phenix_docker
  on:
    branch: master
